name: Run gradle command and create SHA512

inputs:
  gradle-command:
    required: true
    type: string
  intermediate-filepath:
    required: true
    type: string
  final-filepath:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Run gradle command"
      shell: bash
      run: |
        ./gradlew ${{ inputs.gradle-command }}

    - name: "Rename output file"
      shell: bash
      run: mv ${{ inputs.intermediate-filepath }} ${{ inputs.final-filepath }}

    - name: "Generate SHA512 for Linux"
      shell: bash
      if: runner.os == 'Linux'
      run: sha512sum ${{ inputs.final-filepath }} > ${{ inputs.final-filepath }}.sha512
    - name: "Generate SHA512 for Windows"
      shell: bash
      if: runner.os == 'Windows'
      run: certutil -hashfile ${{ inputs.final-filepath }} SHA512 >> ${{ inputs.final-filepath }}.sha512
    - name: "Generate SHA512 for OSX"
      shell: bash
      if: runner.os == 'macOS'
      run: openssl dgst -sha512 > ${{ inputs.final-filepath }}.sha512
